language: java
jdk: openjdk14
install: skip
services:
  - mysql
script:
  - ./gradlew build -s
sudo: false
before_script:
  - mysql -u root -e 'CREATE DATABASE QVS;'
  - mysql -u root QVS < db.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)
